spring:
  application:
    name: item-service

  data:
    mongodb:
      uri: mongodb+srv://vivi:18277003@cluster0.dgyehpa.mongodb.net/itemdb?retryWrites=true&w=majority&appName=Cluster0
server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka