spring:
  application:
    name: account-service

  datasource:
    url: jdbc:mysql://mysql:3306/AccountService
#    url: jdbc:mysql://host.docker.internal:3306/AccountService
    username: root
    password: root
#    password: yc990829
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    com:
      project:
        accountservice:
          security=INFO:
server:
  port: 8082