spring:
  cloud:
    gateway:
      routes:
        - id: item-service
          uri: http://localhost:8081
          predicates:
            - Path=/items/**
        - id: order-service
          uri: http://localhost:8082
          predicates:
            - Path=/orders/**
        - id: payment-service
          uri: http://localhost:8083
          predicates:
            - Path=/payments/**
        - id: account-service
          uri: http://localhost:8084
          predicates:
            - Path =/account/**
eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka
